networks:
  conn:
    external: true
    driver: bridge

services:
  selenium:
    image: selenium/standalone-chrome:latest
    privileged: true
    shm_size: 2g
    ports:
      - '4444:4444'
    networks:
      - conn
    environment:
      - VNC_NO_PASSWORD=1

  web:
    build:
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    volumes:
      - './src:/src'
      - './.env:/src/.env'
    networks:
      - conn
    depends_on:
      - selenium
